apiVersion: v1
kind: Secret
metadata:
  name: cv-secret
  namespace: commvault
  annotations:
    argocd.argoproj.io/sync-wave: "-80"
  labels:
    app.kubernetes.io/name: cv-secret
type: Opaque
stringData:
  user: "installuser"
  password: ""
