apiVersion: v1
kind: ServiceAccount
metadata:
  name: cvpatcher-sa
  namespace: commvault
  annotations:
    argocd.argoproj.io/sync-wave: "-75"
  labels:
    app.kubernetes.io/name: cvpatcher
automountServiceAccountToken: true
