apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: use-anyuid-scc
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
rules:
- apiGroups: ["security.openshift.io"]
  resources: ["securitycontextconstraints"]
  resourceNames: ["anyuid"]
  verbs: ["use"]
